### ISSUE TITLE
linint2  error

### ISSUE THREAD

**Issue by Nety20** [NCAR/GeoCAT#14]
Greetings to you,

I am trying to regrid using GeoCAT, linint2 however I get the following error.

AttributeError: module 'geocat.comp' has no attribute 'linint2'

This is the code I am using 
import numpy as np
import xarray as xr
import geocat.comp
import cartopy.crs as ccrs
import matplotlib.pyplot as plt
from matplotlib import cm
from cartopy.mpl.ticker import LongitudeFormatter, LatitudeFormatter
from cartopy.mpl.geoaxes import GeoAxes
from mpl_toolkits.axes_grid1 import AxesGrid
# Open a netCDF data file using xarray default engine and load the data
# into xarrays
ds = xr.open_dataset("./test.nc")
prec = ds.tp[:]
lat = ds.lat[:]
lon = ds.lon[:]

# Provide (output) interpolation grid and call `linint2` function from
# `geocat-comp`
newlat = np.linspace(min(lat), max(lat), 70)
newlon = np.linspace(min(lon), max(lon), 100)

# Invoke `linint2` from `geocat-comp`
newsst = geocat.comp.linint2(prec, newlon, newlat, False)

**Comment by pilotchute** [comment]
@Nety20 would you please paste the output of `conda list`, as well as the full stack trace of the `AttributeError` here?

**Comment by Nety20** [comment]
@pilotchute  Here is the output for conda list 
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl  
ca-certificates           2020.10.14                    0  
certifi                   2020.6.20          pyhd3eb1b0_3  
cffi                      1.14.0           py38hc512035_1  
chardet                   3.0.4                 py38_1003  
conda                     4.9.2            py38hecd8cb5_0  
conda-package-handling    1.6.1            py38h1de35cc_0  
cryptography              2.9.2            py38ha12b0ac_0  
idna                      2.9                        py_1  
intel-openmp              2019.4                      233  
libcxx                    10.0.0                        1  
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.3                  h0a44026_1  
libgfortran               3.0.1                h93005f0_2  
mkl                       2019.4                      233  
mkl-service               2.3.0            py38hfbe908c_0  
mkl_fft                   1.2.0            py38hc64f4ea_0  
mkl_random                1.1.1            py38h959d312_0  
ncurses                   6.2                  h0a44026_1  
numpy                     1.19.2           py38h456fd55_0  
numpy-base                1.19.2           py38hcfb5961_0  
openssl                   1.1.1h               haf1e3a3_0  
pip                       20.0.2                   py38_3  
pycosat                   0.6.3            py38h1de35cc_1  
pycparser                 2.20                       py_0  
pyopenssl                 19.1.0                   py38_0  
pysocks                   1.7.1                    py38_0  
python                    3.8.3                h26836e1_1  
python.app                2                       py38_10  
readline                  8.0                  h1de35cc_0  
requests                  2.23.0                   py38_0  
ruamel_yaml               0.15.87          py38h1de35cc_0  
scipy                     1.5.2            py38h2515648_0  
setuptools                46.4.0                   py38_0  
six                       1.14.0                   py38_0  
sqlite                    3.31.1               h5c1f38d_1  
tk                        8.6.8                ha441bb4_0  
tqdm                      4.46.0                     py_0  
urllib3                   1.25.8                   py38_0  
wheel                     0.34.2                   py38_0  
xz                        5.2.5                h1de35cc_0  
yaml                      0.1.7                hc338f04_2  
zlib                      1.2.11               h1de35cc_3  

The full stack trace of the AttributeError is as follows

Traceback (most recent call last):
  File "test.py", line 24, in <module>
    newsst = geocat.comp.linint2(prec, newlon, newlat, False)
AttributeError: module 'geocat.comp' has no attribute 'linint2'

**Comment by pilotchute** [comment]
@Nety20 you don't have geocat-comp installed in that conda environment. 
`conda update --all -c conda-forge`
`conda install geocat-comp -c ncar`
and you should be good to go.

**Comment by pilotchute** [comment]
Removed Bug tag for now, as this appears to be solely a support issue.

**Comment by JonReagan** [comment]
I will be following this issue as I have experienced the same error.  I have geocat-comp installed in my environment.  In the Python shell, I noticed that 'linint2' does not appear as an attribute of geocat.comp when running the dir(geocat.comp) command.

**Comment by Nety20** [comment]
Hi, we have tried the running the commands suggested however we are having problems with the python version. Which version would you recommend? We tried 3.8 and 3.6.11.

**Comment by pilotchute** [comment]
Try 3.7 for now. 
if that doesn't work for you, I'd like to let you know that we've been rebasing all of the underlying compiled fortran into a new fortran->python stack. 

If you need a working version of linint2, you can get the non-public release of the replacement stack (which I've personally tested linint2 on) by installing getcat-temp from my personal conda channel akootz 

`conda install geocat-temp -c akootz`

This will then allow you to call linint2 by importing it from geocat.temp

`from geocat.temp import (linint2)`

Please keep me informed here. I do apologize for the problems you've incurred, but that's why we are updating our tech stack. 

p.s. geocat-temp is available on for linux and mac systems, on python versions 3.6, 3.7, 3.8, and 3.9.

**Comment by erogluorhan** [comment]
Hi @Nety20  and @JonReagan ,

Thanks a lot for reaching out to us, and I am sorry to hear about your inconveniences!

I'd like to add a few points to what @pilotchute has already made:

Although we have been publishing the overall `GeoCAT-comp` functionality (including `linint2`) and confirming its usability without any issue for a long while, I just gave a try to a fresh conda environment to replicate your issues as there seems to be a recent change in conda package management system's handling of the package sub-dependency installations that results in strange dependency problems. I was able to replicate the `linint2-cannot-be-imported` issue in my local, and most likely, your issues are due to the same reason, i.e. they are not directly related to `geocat.comp` namespace handling; instead,  they are due to the same recent change in conda package management system. Before talking about your issue, you can find our already existing issue reported to the conda repository [here](https://github.com/conda/conda/issues/10344); however, we could not get a response yet, unfortunately. Please have a look at the issue details in that link, but briefly, conda is not installing the latest available versions of `geocat.comp` subdependencies (which are `geocat.ncomp` and `libncomp`). In fact, as an end-user, you shouldn't be concerned about these subdependencies as their latest versions should have been invisibly installed by the conda package management system; however, this recent `conda` behavior of the last few weeks leads to the older versions being installed. Hopefully, we can find what's going on at the conda side recently and solve this issue soon.

My guess is that you are having your issues in relation to this same behavior I described above. To confirm it, I'd like to ask you to run a `conda list` command in your `geocat.comp` environment (The one @Nety20 provided above in this conversation was apparently not from his/her `geocat.comp` environment). A healthy conda installation should have all **versions 0.2** of `geocat.comp`, `geocat.ncomp`, and `libncomp` packages (which was the case until a few weeks ago), but I guess that the recent strange conda behavior should have resulted in the installation of **version 0.2** `geocat.comp` but **versions 0.1a** `geocat.ncomp` and `ncomp` packages in your environments. Please let me know if it is the case. If it is the case, I will suggest a quick fix to it until we figure out what is going on with conda for a permanent solution.

Hope this helps.

Orhan @ GeoCAT

**Comment by Nety20** [comment]
@ erogluorhan

Hi Thanks a lot for the detailed explanation. I have run conda list in geocat environment and I see the different versions you are referring to. Here is the output:

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
argon2-cffi               20.1.0           py36h1d69622_2    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
bleach                    3.2.1              pyh9f0ad1d_0    conda-forge
bokeh                     2.2.3            py36h5fab9bb_0    conda-forge
boost-cpp                 1.74.0               h9359b55_0    conda-forge
bzip2                     1.0.8                h516909a_3    conda-forge
c-ares                    1.17.1               h36c2ea0_0    conda-forge
ca-certificates           2020.11.8            ha878542_0    conda-forge
cairo                     1.16.0            h488836b_1006    conda-forge
cartopy                   0.18.0           py36ha922973_5    conda-forge
certifi                   2020.11.8        py36h5fab9bb_0    conda-forge
cffi                      1.14.4           py36h211aa47_0    conda-forge
cfitsio                   3.470                h2e3daa1_7    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
contextvars               2.4                        py_0    conda-forge
curl                      7.71.1               he644dc0_8    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.11.0           py36h8c4c3a4_1    conda-forge
dask                      2.30.0                     py_0    conda-forge
dask-core                 2.30.0                     py_0    conda-forge
dbus                      1.13.6               hfdff14a_1    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
distributed               2.30.1           py36h5fab9bb_0    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
esmf                      8.0.1           nompi_hcaa3220_2    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
fontconfig                2.13.1            h7e3eb15_1002    conda-forge
freetype                  2.10.4               h7ca028e_0    conda-forge
freexl                    1.0.5             h516909a_1002    conda-forge
fsspec                    0.8.4                      py_0    conda-forge
geocat-comp               0.2                        py_0    ncar
geocat-ncomp              0.1a             py36h785e9b2_0    ncar
geos                      3.8.1                he1b5a44_0    conda-forge
geotiff                   1.6.0                h5d11630_3    conda-forge
gettext                   0.19.8.1          hf34092f_1004    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
glib                      2.66.3               h58526e2_0    conda-forge
gsl                       2.6                  hf94e986_0    conda-forge
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.14.5               h36ae1b5_2    conda-forge
hdf4                      4.2.13            hf30be14_1003    conda-forge
hdf5                      1.10.6          nompi_h7c3c948_1111    conda-forge
hdfeos2                   2.20              h64bfcee_1000    conda-forge
hdfeos5                   5.1.16               hb4ce793_7    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icu                       67.1                 he1b5a44_0    conda-forge
immutables                0.14             py36h8c4c3a4_1    conda-forge
importlib-metadata        3.1.0              pyhd8ed1ab_0    conda-forge
importlib_metadata        3.1.0                hd8ed1ab_0    conda-forge
ipykernel                 5.3.4            py36he448a4c_1    conda-forge
ipython                   7.16.1           py36h95af2a2_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1              pyh9f0ad1d_1    conda-forge
jasper                    1.900.1           h07fcdf6_1006    conda-forge
jedi                      0.17.2           py36h5fab9bb_1    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
json-c                    0.13.1            hbfbb72e_1002    conda-forge
jsonschema                3.2.0                      py_2    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            6.1.7                      py_0    conda-forge
jupyter_console           6.2.0                      py_0    conda-forge
jupyter_core              4.7.0            py36h5fab9bb_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
kealib                    1.4.13               h33137a7_1    conda-forge
kiwisolver                1.3.1            py36h51d7077_0    conda-forge
krb5                      1.17.2               h926e7f8_0    conda-forge
lcms2                     2.11                 hcbb858e_1    conda-forge
ld_impl_linux-64          2.35.1               hed1e6ac_0    conda-forge
libblas                   3.9.0                3_openblas    conda-forge
libcblas                  3.9.0                3_openblas    conda-forge
libclang                  10.0.1          default_hde54327_1    conda-forge
libcurl                   7.71.1               hcdd3856_8    conda-forge
libdap4                   3.20.6               h1d1bd15_1    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               hcdb4288_3    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
libgdal                   3.1.4                h670eac6_0    conda-forge
libgfortran-ng            7.5.0               hae1eefd_17    conda-forge
libgfortran4              7.5.0               hae1eefd_17    conda-forge
libglib                   2.66.3               hbe7bbb4_0    conda-forge
libgomp                   9.3.0               h5dbcf3e_17    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libkml                    1.3.0             h74f7ee3_1012    conda-forge
liblapack                 3.9.0                3_openblas    conda-forge
libllvm10                 10.0.1               he513fc3_3    conda-forge
libnetcdf                 4.7.4           nompi_hefab0ff_106    conda-forge
libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
libopenblas               0.3.12          pthreads_hb3c22a3_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     12.3                 h5513abc_2    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libspatialite             5.0.0                h4dde289_0    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
libtiff                   4.1.0                h4f3a223_6    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp-base              1.1.0                h36c2ea0_3    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              0.10.0               he1b5a44_0    conda-forge
libxml2                   2.9.10               h68273f3_2    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.9.2                he1b5a44_3    conda-forge
markupsafe                1.1.1            py36he6145b8_2    conda-forge
matplotlib                3.3.3            py36h5fab9bb_0    conda-forge
matplotlib-base           3.3.3            py36he12231b_0    conda-forge
mistune                   0.8.4           py36h1d69622_1002    conda-forge
msgpack-python            1.0.0            py36h51d7077_2    conda-forge
mysql-common              8.0.21                        2    conda-forge
mysql-libs                8.0.21               hf3661c5_2    conda-forge
nbclient                  0.5.1                      py_0    conda-forge
nbconvert                 6.0.7            py36h5fab9bb_3    conda-forge
nbformat                  5.0.8                      py_0    conda-forge
ncl                       6.6.2               h087f628_23    conda-forge
ncomp                     0.1a                 h1c2f66e_1    ncar
ncurses                   6.2                  h58526e2_4    conda-forge
nest-asyncio              1.4.3              pyhd8ed1ab_0    conda-forge
netcdf-fortran            4.5.3           nompi_hfef6a68_101    conda-forge
notebook                  6.1.5            py36h5fab9bb_0    conda-forge
nspr                      4.29                 he1b5a44_1    conda-forge
nss                       3.59                 h2c00c37_0    conda-forge
numpy                     1.19.4           py36h8732dcd_1    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.3.1                h981e76c_3    conda-forge
openssl                   1.1.1h               h516909a_0    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandas                    1.1.4            py36hd87012b_0    conda-forge
pandoc                    2.11.2               h36c2ea0_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.7.1              pyh9f0ad1d_0    conda-forge
partd                     1.1.0                      py_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.0.1            py36h10ecd5c_0    conda-forge
pip                       20.2.4                     py_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
poppler                   0.89.0               h4190859_1    conda-forge
poppler-data              0.4.10                        0    conda-forge
postgresql                12.3                 h8573dbc_2    conda-forge
proj                      7.1.1                h966b41f_3    conda-forge
prometheus_client         0.9.0              pyhd3deb0d_0    conda-forge
prompt-toolkit            3.0.8              pyha770c72_0    conda-forge
prompt_toolkit            3.0.8                hd8ed1ab_0    conda-forge
psutil                    5.7.3            py36he6145b8_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.7.2                      py_0    conda-forge
pyngl                     1.6.1            py36h174697a_2    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py36haa643ae_4    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.17.3           py36h1d69622_1    conda-forge
pyshp                     2.1.2              pyh9f0ad1d_0    conda-forge
python                    3.6.11          h4d41432_2_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.6                     1_cp36m    conda-forge
pytz                      2020.4             pyhd8ed1ab_0    conda-forge
pyyaml                    5.3.1            py36he6145b8_1    conda-forge
pyzmq                     20.0.0           py36h2b1bd32_1    conda-forge
qt                        5.12.9               h1f2b2cb_0    conda-forge
qtconsole                 5.0.1              pyhd8ed1ab_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.6.0           py36h9880bd3_2    conda-forge
shapely                   1.7.1            py36h15bcdef_1    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sortedcontainers          2.3.0              pyhd8ed1ab_0    conda-forge
sqlite                    3.33.0               h4cf870e_1    conda-forge
tblib                     1.6.0                      py_0    conda-forge
terminado                 0.9.1            py36h5fab9bb_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tiledb                    2.1.3                h17508cd_0    conda-forge
tk                        8.6.10               hed695b0_1    conda-forge
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.1              py36h1d69622_0    conda-forge
traitlets                 4.3.3            py36h9f0ad1d_1    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
tzcode                    2020a                h516909a_0    conda-forge
udunits2                  2.2.27.6          h4e0c4b3_1001    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
widgetsnbextension        3.5.1            py36h5fab9bb_4    conda-forge
xarray                    0.16.1                     py_0    conda-forge
xerces-c                  3.2.3                hfe33f54_1    conda-forge
xorg-imake                1.0.7                         0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.12               h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxaw               1.0.13            h516909a_1002    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxmu               1.1.3                h516909a_0    conda-forge
xorg-libxpm               3.5.13               h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-libxt                1.1.5             h516909a_1003    conda-forge
xorg-makedepend           1.0.6                he1b5a44_1    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zeromq                    4.3.3                h58526e2_3    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.4.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.5                h6597ccf_2    conda-forge

**Comment by erogluorhan** [comment]
@Nety20 thanks a lot for letting me know your output! That is exactly what I was referring to. I could suggest a quick fix then:

Please run the following code (when your `geocat-com` conda environment is activated)

`conda install geocat-ncomp=0.2 libncomp=0.2 -c ncar`

After this, you may want to check `conda list` once again to see you have **version 0.2** of both `geocat-ncomp` and `libncomp` are installed then. If so, you should be good to call `linint2`.

Please let me know if/when this solves your issue.

Thanks!

Orhan - GeoCAT

**Comment by JonReagan** [comment]
@erogluorhan and @pilotchute , thank you so much for all of your help!   

Erogluorhan, your suggestion of forcing the correct version worked perfectly for me.  I could see in my package list that I too had the incorrect versions installed initially.  After running your command to force the correct version, I was able to run the example file with no issues (after installing scipy and pykdtree, two dependencies I must have missed during my install).  I'm very excited to be up and running.  Thanks again for your help!

**Comment by erogluorhan** [comment]
@JonReagan , glad to hear it worked for you! Again, a normal conda installation should already have installed those latest versions of sub-dependencies, but it is good that we can force them manually. Anyway, we will be working on this conda issue to overcome that for a permanent solution that should be invisible to the end user as it was before.

Stay tuned for GeoCAT-comp's upcoming new functionalities soon!

Thanks!

Orhan - GeoCAT

**Comment by Nety20** [comment]
@erogluorhan  Thank you very much this fix works very well. Really appreciate the support.

**Comment by erogluorhan** [comment]
Glad to hear, @Nety20 ! 

Thanks again for bringing this issue to our attention!

Orhan - GeoCAT
