### ISSUE TITLE
Installation UnsatisfiableError with conda on macOS

### ISSUE THREAD

**Issue by mkorotkin** [NCAR/GeoCAT#15]
I have attempted to install geocat-comp on a 2020 iMac running Catalina. I've tried installing it on Python 3.6 and 3.7 and I keep getting this error:

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

The environment is brand new and has nothing in it except what anaconda installs when I create a new environment. I've attempting creating a new environment both through the GUI in Anaconda Navigator or through a terminal window. The same error is shown. It attempts to download the library and then stops before it reaches 100% and throws that error with no additional information. 

Thank you.

**Comment by erogluorhan** [comment]
Hi @mkorotkin ,

Sorry for the inconvenience you are currently having.

Could you please copy and past the output when you run `conda info` in your terminal? In addition, it would be also helpful if you can provide what commands you are using to install `geocat-comp`?

Orhan at GeoCAT

**Comment by mkorotkin** [comment]
Thank you for the quick reply! 

     active environment : GEOCAT-COMP
    active env location : /opt/anaconda3/envs/GEOCAT-COMP
            shell level : 2
       user config file : /Users/mikhailk/.condarc
 populated config files : /Users/mikhailk/.condarc
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __osx=10.15.7
       base environment : /opt/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/anaconda3/pkgs
                          /Users/mikhailk/.conda/pkgs
       envs directories : /opt/anaconda3/envs
                          /Users/mikhailk/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Darwin/19.6.0 OSX/10.15.7
                UID:GID : 501:20
             netrc file : None
           offline mode : False

**Comment by erogluorhan** [comment]
In addition, it would be also helpful if you can provide what commands you are using to install `geocat-comp`.

**Comment by mkorotkin** [comment]
Sure. 

conda install -c ncar geocat-comp

**Comment by erogluorhan** [comment]
Thanks!

In your current activated environment, could you also run `conda list` and send me over the output?

While I am looking on that, you may want to update your conda from 4.8.2 to 4.9.2 by running `conda update conda` and then giving `geocat-comp` installation another shot.

**Comment by mkorotkin** [comment]
# packages in environment at /opt/anaconda3/envs/GEOCAT-COMP:
#
# Name                    Version                   Build  Channel
ca-certificates           2020.12.8            hecd8cb5_0  
certifi                   2020.12.5        py36hecd8cb5_0  
libcxx                    10.0.0                        1  
libedit                   3.1.20191231         h1de35cc_1  
libffi                    3.3                  hb1e8313_2  
ncurses                   6.2                  h0a44026_1  
openssl                   1.1.1i               h9ed2024_0  
pip                       20.3.3           py36hecd8cb5_0  
python                    3.6.12               h26836e1_2  
readline                  8.0                  h1de35cc_0  
setuptools                51.1.2           py36hecd8cb5_4  
sqlite                    3.33.0               hffcf06c_0  
tk                        8.6.10               hb0a8c7a_0  
wheel                     0.36.2             pyhd3eb1b0_0  
xz                        5.2.5                h1de35cc_0  
zlib                      1.2.11               h1de35cc_3

**Comment by mkorotkin** [comment]
Just to let you know I have updated my conda and this did not resolve the issue unfortunately.

**Comment by erogluorhan** [comment]
Ok, thanks! I think I have one suspect in your environment:

Your channel URLs are:
https://repo.anaconda.com/pkgs/main/osx-64
https://repo.anaconda.com/pkgs/main/noarch
https://repo.anaconda.com/pkgs/r/osx-64
https://repo.anaconda.com/pkgs/r/noarch

Thisi is mostly because you installed Anaconda (instead of smaller `miniconda3` that only includes `conda` package). Please try to add conda-forge channels into your environment. There are several documentations on this online, but I think the following should just work:

`conda config --add channels conda-forge`

Then see if you have the following channel URLs:

https://conda.anaconda.org/conda-forge/osx-64
https://conda.anaconda.org/conda-forge/noarch

After that, I recommend removing the environment "GEOCAT-COMP" because it might be broken due to errors. Run this:

`conda env remove --name GEOCAT-COMP`

Finally run the following command to install `geocat-comp`:

```
conda create --name geocat-comp python=3.8
conda install geocat-comp geocat-ncomp=0.2 libncomp=0.2 -c ncar
```

Please let me know if it works.

**Comment by erogluorhan** [comment]
Additionally, if you are planning to use NCAR channel packages frequently, you may also want to add NCAR channel as follows:

`conda config --add channels ncar`

which help you get rid of typing `-c ncar` when installing packages from NCAR's conda channel.

**Comment by mkorotkin** [comment]
I've followed the instructions and it's taking a very very long time to attempt to download/install the dependancies.

Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining conflict for pytest-doctestplus pkginfo pydocstyle pyyaml pytest-arraydiff backports navigator-updater pytest-astropy pandocfilters/ 

It took about 20 minutes to resolve the environment which was unusual.

**Comment by mkorotkin** [comment]
Several hours later and its still examining conflicts. I feel something is wrong here as I've never had this take this long.

**Comment by mkorotkin** [comment]
Update: It has finally finished and has said that there is a conflict with every package and dependency so I'm not sure what's going on at this point.

**Comment by erogluorhan** [comment]
@pilotchute Any ideas on this?
