### ISSUE TITLE
register geocat.ucar.edu web site

### ISSUE THREAD

**Issue by clyne** [NCAR/GeoCAT#2]
We need to register a geocat.ucar.edu (or similar) URL and link to our splash page

**Comment by khallock** [comment]
I found [this GitHub documentation page](https://help.github.com/en/articles/using-a-custom-domain-with-github-pages) describing how to configure a GitHub Pages site to work on a custom domain, commenting here to bookmark it.

**Comment by clyne** [comment]
Scott has been through this process with VAPOR and could be a resource for this

**Comment by khallock** [comment]
https://geocat.ucar.edu is now live.
