### ISSUE TITLE
Links from the splash page are broken

### ISSUE THREAD

**Issue by clyne** [NCAR/GeoCAT#3]
All of the links from geocat.ucar.edu are broken. E.g. 

For example, clicking on Documentation generates a 404 with the following url: 

https://geocat.ucar.edu/GeoCAT/pages/documentation.html

**Comment by khallock** [comment]
Thanks for the heads up, I just fixed this. It was a result of the domain change removing the need for "/GeoCAT" in the URL:
```https://ncar.github.io/GeoCAT/pages/documentation.html```
is now
```https://geocat.ucar.edu/pages/documentation.html```
