### ISSUE TITLE
Errors in creating new environment on remote server

### ISSUE THREAD

**Issue by eroesler** [NCAR/GeoCAT#32]
In installing GeoCAT on a remote computer,  I get an error when the environment is being solved.   The syntax of the error is below.    I cannot control the conda version on the system, if that is driving the error.  It is a pre-loaded module on the system.  I tried updating it as suggested, but that fails, too.  Suggestions are greatly appreciated, even if they are to abandon because it is not possible to complete on the remote system.  Thank you for your help.  

------
.......[user@....]GeoCAT-examples (main)$ conda env create -f conda_environment.yml -n geocat-examples
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 4.5.8
  latest version: 4.10.1

Please update conda by running

    $ conda update -n base -c defaults conda

Downloading and Extracting Packages
_openmp_mutex-4.5    |   22 KB | ####################################################################################################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(502): An error occurred while installing package 'conda-forge::alabaster-0.7.12-py_0'.
OSError(2, 'No such file or directory')
Attempting to roll back.

Rolling back transaction: done

OSError(2, 'No such file or directory')

**Comment by anissa111** [comment]
@eroesler I apologize, this issue seems to have fallen through the cracks. Are you still having this issue?

**Comment by marodrig** [comment]
@eroesler Following up on this issue, is the error still showing up?

**Comment by marodrig** [comment]
Closing as undone, for the time being.
