### ISSUE TITLE
example data sets needed

### ISSUE THREAD

**Issue by clyne** [NCAR/GeoCAT#4]
We need a place on the web site to collect sample data sets to be used for examples, tutorials, etc. The VAPOR team is making use of Eric Nienhouse's groups data services platform (can't remember which acronym, CDP?) to host the VAPOR example data sets. We may want to follow suit, and possibly share data sets with the VAPOR team.

**Comment by erogluorhan** [comment]
https://github.com/NCAR/geocat-datafiles
