### ISSUE TITLE
module geocat.comp has no attribute rgrid2rcm

### ISSUE THREAD

**Issue by jaredalee** [NCAR/GeoCAT#40]
Hi, I'm wondering if you can help me. This is the first time I've tried to use geocat routines in my Python scripts (I'm a former NCL user, but have fully pivoted to Python). I'm trying to regrid data from a rectilinear grid onto a curvilinear grid, so I'm trying to use the routine rgrid2rcm, following the documentation on the webpage (https://geocat-comp.readthedocs.io/en/latest/user_api/generated/geocat.comp.rgrid2rcm.html).

```
import geocat
import geocat.comp

[ a bunch of lines where I obtain lat/lon and the variable from the rectilinear CAMS data and the lat/lon from the curvilinear CMAQ grid from my data ]

cams_pm25_regrid = geocat.comp.rgrid2rcm(cams_lat, cams_lon, cams_pm25, cmaq_lat, cmaq_lon)
```

Running that yields this error:

`AttributeError: module 'geocat.comp' has no attribute 'rgrid2rcm'`

Am I doing something wrong? I currently have geocat-comp (2021.10.0) and geocat-f2py (2021.8.0).

Thanks,
Jared

**Comment by jaredalee** [comment]
One more thing that I tried was to include:

`from geocat.comp import rgrid2rcm`

When I do that, then I get this error:

```
Traceback (most recent call last):
  File "regrid_cams_to_cmaq.py", line 30, in <module>
    from geocat.comp import rgrid2rcm
ImportError: cannot import name 'rgrid2rcm' from 'geocat.comp' (/glade/work/jaredlee/python/my_npl_clone_20200417_casper_3.7.5/lib/python3.7/site-packages/geocat/comp/__init__.py)
```

Also, I'm running on NCAR's Casper.

**Comment by jaredalee** [comment]
Note that I've just posted this as Issue 199 in the geocat-comp github (https://github.com/NCAR/geocat-comp/issues/199), as I expect that's the better venue to get attention/help.

**Comment by erogluorhan** [comment]
Hi @jaredalee , thanks a lot for reaching out! Even though we can follow the issues that come to any of our repositories, you are right with opening the [GeoCAT-comp Issue #199](https://github.com/NCAR/geocat-comp/issues/199) as this is something related to GeoCAT-comp. 

I am closing this now, and we can follow at GeoCAT-comp
