### ISSUE TITLE
Refresh content on landing page

### ISSUE THREAD

**Issue by clyne** [NCAR/GeoCAT#45]
The overview on the GeoCAT [landing page](https://geocat.ucar.edu/) is looking a little too NCL focused. This is fine for NCL users wanting to move to Python. But for potential new users that do not have familiarity with NCL it may not be the message we want to convey. I think that it is a good idea to include language relating to GeoCAT's NCL origins (to guide NCL users), but we should also be clear about what GeoCAT provides for users with no NCL background. I.e. Python tools for analyzing/visualizing Earth System Science data, e.g. climate, weather, atmosphere, etc., etc.

It would probably also be a good idea to call out GeoCAT's relation to Pangeo (GeoCAT builds upon the Pangeo "core" stack, Xarray, Dask, Jupyter Notebooks). The Pangeo brand recognition is really important here. We want visitors to the site to understand that GeoCAT plays well with the Pangeo ecosystem.

**Comment by erogluorhan** [comment]
Yes, I agree with all of these. We were currently in the process of updating our user-facing documentation, and this is a great input to take into consideration for the GeoCAT homepage.
