### ISSUE TITLE
Add a web accessibility link

### ISSUE THREAD

**Issue by kafitzgerald** [NCAR/GeoCAT#67]
As @jukent pointed out over on NCAR/ESDS#267, we need to add a web accessibility link in the footer per institutional guidance by 2/1/24.  

The way the recommendations read we should probably be doing this on our GeoCAT documentation pages as well.  Those aren't on a UCAR domain though and don't have a footer at the moment.  Thoughts?

**Comment by jukent** [comment]
I don't know if the package documentation pages need to? But the GeoCAT one should. The template has been updated, but it looks like we're using an older version of the template?

**Comment by kafitzgerald** [comment]
Interesting.  Yeah, the template repo we're currently using is now archived.  

I imagine we should probably update.  

@erogluorhan, any thoughts?

**Comment by erogluorhan** [comment]
> Interesting. Yeah, the template repo we're currently using is now archived.
> 
> I imagine we should probably update.
> 
> @erogluorhan, any thoughts?

I've created PR #68 for this (hoping it to be as easy as bumping the koru-jekyll theme to the latest version where they've added Accesibility link). 

Regarding the GeoCAT docs websites, I agree with @jukent , they are not on UCAR or NSF NCAR domains, so I don't think we'd need to update them.
