### ISSUE TITLE
Installation UnsatisfiableError with conda on macOS

### ISSUE THREAD

**Issue by ipisso** [NCAR/GeoCAT#7]
Hi, 

I followed the installation instructions from 
https://geocat-comp.readthedocs.io/en/latest/installation.html

and I got the following "UnsatisfiableError " error:

$ conda create -n geocat -c conda-forge -c ncar geocat-comp pyngl matplotlib cartopy jupyter
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - geocat-comp -> ncomp -> libgfortran >=4.0.0,<5.0.0.a0
  - geocat-comp -> python >=3.7,<3.8.0a0
  - geocat-comp -> python_abi 3.6.* *_cp36m
  - python 2.7*
Use "conda info <package>" to see the dependencies for each package.

Have you experienced this before?

I am using conda 4.3.30 on a MacBook Pro 2019 with macOS Mojave 10.14.6  

Thanks,

Ignacio

**Comment by pilotchute** [comment]
@ipisso the conflict is between python 2.7 and geocat-comp which requires python 3.6 or higher. 

make a conda environment with python 3.7, and install geocat-comp in that environment. 

`conda create --name geocat-conda python=3.7`
`conda activate geocat-conda`
`conda install geocat-comp`

**Comment by clyne** [comment]
@pilotchute do we need to update our documentation to reflect the python 3.x requirement?

**Comment by ipisso** [comment]
Thanks for your reply! I followed your advice and I get the following error:

PackagesNotFoundError: The following packages are not available from current channels:

I tried different variations referring to conda-forge without luck.

Should I add a specific  alternate channel? 

Thanks


(geocat-conda) 06.18 13.33 ignacio@Raumariki:~$conda install geocat-comp
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - geocat-comp

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


(geocat-conda) 06.18 13.35 ignacio@Raumariki:~$conda install -c conda-forge  geocat-comp
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - geocat-comp

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


(geocat-conda) 06.18 13.38 ignacio@Raumariki:~$conda config --append channels conda-forge
(geocat-conda) 06.18 13.38 ignacio@Raumariki:~$conda install geocat-comp
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - geocat-comp

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by ipisso** [comment]
Thank you for the help. I think I needed the ncar channel (-c ncar?). 

Now I am running the example from

https://geocat-comp.readthedocs.io/en/latest/examples.html#geocat-comp-linint2-points-example

I get an the error in line 22:

>>> newsst = geocat.comp.linint2(sst, newlon, newlat, False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'geocat.comp' has no attribute 'linint2'

If I ask

dir(geocat.comp)
['AttributeError', 'ChunkError', 'CoordinateError', 'DimensionError', 'Error', 'Iterable', 'MetaError', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'da', 'detrend', 'map_blocks', 'ndpolyfit', 'ndpolyval', 'np', 'polynomial', 'version', 'xr']

python doesn't find 
"linint2"

**Comment by erogluorhan** [comment]
> Thank you for the help. I think I needed the ncar channel (-c ncar?).

That's correct. Can we assume you ran this code and successfully set up your environment then?


> Now I am running the example from
> 
> https://geocat-comp.readthedocs.io/en/latest/examples.html#geocat-comp-linint2-points-example
> 
> I get an the error in line 22:
> 
> > > > newsst = geocat.comp.linint2(sst, newlon, newlat, False)
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > AttributeError: module 'geocat.comp' has no attribute 'linint2'
> 

You are trying to run `mpl_linint2.py `example script, right? What is the active conda environment when you are running this code? Can you provide the output of `conda list` for that active conda environment please?

**Comment by pilotchute** [comment]
@ipisso checking in, has your status changed? I'll be closing this support request as stale in a week pending your reply.

**Comment by ipisso** [comment]
I will look at it again now.

**Comment by erogluorhan** [comment]
Hi @ipisso , any updates?

**Comment by pilotchute** [comment]
Closing due to lack of response.
