### ISSUE TITLE
Add git pre-commit hook to ensure proper formatting and PEP8 conformance

### ISSUE THREAD

**Issue by clyne** [NCAR/GeoCAT#8]
We should run "black" and/or flake8 to automatically format code on commit.

**Comment by erogluorhan** [comment]
@pilotchute this issue has been indeed opened a while ago, but please evaluate this also with the team comments at [GeoCAT-examples Issue #231](https://github.com/NCAR/GeoCAT-examples/issues/231), and we should figure out how to proceed.
