### ISSUE TITLE
Website is not reachable

### ISSUE THREAD

**Issue by richelbilderbeek** [NCAR/GeoCAT#81]
**Describe the bug**

When I go to [https://geocat.ucar.edu/](https://geocat.ucar.edu/) I get a 404 error:

![Screenshot from 2024-12-04 08-42-13](https://github.com/user-attachments/assets/c2ae08c3-082b-4428-8175-1b569faec89c)

**To Reproduce**

1. Go to [https://geocat.ucar.edu/](https://geocat.ucar.edu/)

**Expected behavior**

I expected to see a website.

**Screenshots**

See above.

**Enviroment (please complete the following information):**

 - OS: Ubuntu 24.04
 - Python: NA
 - GeoCAT: NA

**Additional context**

None.

**Comment by kafitzgerald** [comment]
Hi @richelbilderbeek, thanks for the note!

I think some folks were working on getting a new site transferred over to this domain yesterday.  Hopefully we'll have this sorted soon.

**Comment by richelbilderbeek** [comment]
Website is up again! Closing this issue :+1:
